set -s escape-time 0

set -ga terminal-overrides alacritty:RGB

set -g history-limit 100000

set -g prefix C-a
set -g mode-keys vi
set -g status-keys vi
set -g mouse on

set -g pane-border-indicators off
set -g pane-active-border-style none

set -g status-justify centre
set -g status-style fg=white,bg=brightblack
set -g status-left ' #S '
set -g status-left-length 30
set -g status-right ' #h '
set -g status-right-length 90

set -g window-status-format '#[none]#I:#[fg=green]#W#[none]#F'
set -g window-status-current-format '#[none]#I:#[fg=brightgreen,bold]#W#[none]#F'

set -g set-titles on
set -g set-titles-string '#S:#W'

unbind C-b

bind C-a send-prefix
bind '"' split-window -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'
